name: rick_morty_app
description: List characters from Rick and Morty universe.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ^3.22.3

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  http: ^1.1.0
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.5.2
  provider: ^6.0.5

dev_dependencies:
  dart_pre_commit: ^5.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  git_hooks: ^1.0.1

flutter:
  uses-material-design: true
